---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by boshi.
--- DateTime: 2026/3/24 8:17
---

-- 比较线程标识雨锁中的标识是否一致
if(redis.call('get', KEYS[1]) == ARGV[1]) then
    -- 释放锁 del key
    return redis.call('del', KEYS[1])
end
return 0